[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/cloudflare/cloudflare-go"
  version = "0.9.4"

[[constraint]]
  name = "github.com/caarlos0/env"
  version = "6.0.0"
